import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import App from "@/component/App/App";
import { Footer, Header } from "@/component";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <App>
        <body className='flex flex-col h-screen'>
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
        </body>
      </App>
    </html>
  );
}
